### ISSUE TITLE
多图分享到朋友圈停在添加多图对话框

### ISSUE THREAD

**Issue by QiChaoLau** [shichaohui/WXShareMultiImage#1]
只能添加1张，没有添加到多张

**Comment by shichaohui** [comment]
是否开启了无障碍服务？添加多图对话框具体是指选择相机或者相册的弹窗吗？

**Comment by QiChaoLau** [comment]
对，已经开启了，首次分享停留在选择相机或者相册的弹窗，后面好像在微信页面，APP停止运行了，后面就直接只添加一张图，没有弹窗

**Comment by shichaohui** [comment]
分享的文字会自动粘贴吗？你的系统语言是不是英文？

**Comment by QiChaoLau** [comment]
会自动粘贴，系统语言是中文。

**Comment by shichaohui** [comment]
有错误日志吗？弹窗的选项里有“从相册选择”吗？文字需要 100% 匹配。你的手机机型和系统版本是什么？

**Comment by QiChaoLau** [comment]
pixel2,android9.0，文字是一样的，我的微信也是6.7.3，报错信息：
2018-11-09 18:14:06.290 26564-27051/? I/AppStateWatcher: isFront:false
2018-11-09 18:14:07.331 26564-27051/? I/AppStateWatcher: isFront:false
2018-11-09 18:14:07.372 614-614/? D/SurfaceFlinger: duplicate layer name: changing com.msyc.onion/com.msyc.onion.ui.activities.MaterialShareActivity to com.msyc.onion/com.msyc.onion.ui.activities.MaterialShareActivity#1
2018-11-09 18:14:07.453 751-751/? I//vendor/bin/hw/android.hardware.health@2.0-service.wahoo: SRAM data: 2483520
2018-11-09 18:14:07.456 1820-1820/? E/QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
2018-11-09 18:14:07.456 1820-1820/? E/QtiImsExtUtils: isCarrierConfigEnabled bundle is null
2018-11-09 18:14:08.203 1187-1187/? V/SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
2018-11-09 18:14:08.359 26564-27051/? I/AppStateWatcher: isFront:false
2018-11-09 18:14:08.361 6861-31621/? I/EventLogSendingHelper: Sending log events.
2018-11-09 18:14:08.396 6861-6861/? I/WorkerManager: dispose()
2018-11-09 18:14:09.365 26564-27051/? I/AppStateWatcher: isFront:false
2018-11-09 18:14:09.467 2021-4535/? E/NetworkScheduler.ATC: Trying to release unacquired lock: com.google.android.gms/.clearcut.uploader.QosUploaderService
2018-11-09 18:14:09.535 2021-19375/? E/NetworkScheduler: Invalid component specified.
2018-11-09 18:14:09.850 2021-8005/? E/NetworkScheduler: Invalid component specified.
2018-11-09 18:14:09.906 2021-2034/? I/.gms.persisten: Background concurrent copying GC freed 426624(18MB) AllocSpace objects, 21(892KB) LOS objects, 49% free, 19MB/39MB, paused 51us total 196.912ms
2018-11-09 18:14:09.967 2021-19375/? E/NetworkScheduler: Invalid component specified.
2018-11-09 18:14:10.162 2021-8005/? E/NetworkScheduler: Invalid component specified.
2018-11-09 18:14:10.311 1187-1649/? I/ActivityManager: START u0 {act=android.intent.action.SEND_MULTIPLE typ=image/* cmp=com.tencent.mm/.ui.tools.ShareToTimeLineUI (has extras)} from uid 10300
2018-11-09 18:14:10.313 767-767/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: LAUNCH ON
2018-11-09 18:14:10.329 9300-9300/com.msyc.onion D/CrashReport: >>> com.msyc.onion.ui.activities.MaterialShareActivity onPaused <<<
2018-11-09 18:14:10.331 1187-12732/? D/ActivityManager: Raise procstate to external provider: ProcessRecord{698fe3d 9354:com.msyc.onion:pushcore/u0a300}
2018-11-09 18:14:10.339 4858-4858/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b8c40c3
2018-11-09 18:14:10.388 26564-27051/? I/AppStateWatcher: isFront:false
2018-11-09 18:14:10.423 4858-4858/? W/Bundle: Key android.intent.extra.TEXT expected String but value was a java.util.ArrayList.  The default value <null> was returned.
2018-11-09 18:14:10.426 4858-4858/? W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1158)
        at android.content.Intent.getStringExtra(Intent.java:7445)
        at com.tencent.mm.sdk.platformtools.t.j(SourceFile:115)
        at com.tencent.mm.ui.tools.ShareToTimeLineUI.a(SourceFile:361)
        at com.tencent.mm.pluginsdk.ui.AutoLoginActivity.onCreate(SourceFile:67)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-11-09 18:14:10.492 614-2631/? W/SurfaceFlinger: Attempting to set client state on removed layer: com.msyc.onion/com.msyc.onion.ui.activities.MaterialShareActivity#1
2018-11-09 18:14:10.492 614-2631/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=12848#0
2018-11-09 18:14:10.492 614-2631/? W/SurfaceFlinger: Attempting to destroy on removed layer: com.msyc.onion/com.msyc.onion.ui.activities.MaterialShareActivity#1
2018-11-09 18:14:10.492 614-2631/? W/SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=12848#0
2018-11-09 18:14:10.335 1187-12732/? D/ActivityManager: Raise procstate to external provider: ProcessRecord{698fe3d 9354:com.msyc.onion:pushcore/u0a300}
2018-11-09 18:14:10.507 4858-4858/? E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted
2018-11-09 18:14:10.525 614-614/? D/SurfaceFlinger: duplicate layer name: changing com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI to com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI#1
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: QBAR_ERR : Java_com_tencent_qbar_QbarNative_Init
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: detection_model_path_:/data/data/com.tencent.mm/files/qbar/detect_model.bin
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: init id:0
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: searchMode:1
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: inputCharset:ANY
2018-11-09 18:14:10.539 4858-4906/? I/native-tag: outputCharset:UTF-8
2018-11-09 18:14:10.551 4858-4906/? I/native-tag: qbar init rst 0 
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: QBAR_ERR : Java_com_tencent_qbar_QbarNative_SetReaders
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: SetReaders id:0
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: v_reader_0:1
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: v_reader_1:2
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: v_reader_2:3
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: v_reader_3:4
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: QBAR_ERR : Java_com_tencent_qbar_QbarNative_ScanImage
2018-11-09 18:14:10.553 4858-4906/? I/native-tag: QBAR_ERR : Java_com_tencent_qbar_QbarNative_ScanImage, w 362 h 271
2018-11-09 18:14:10.577 1187-1224/? I/ActivityManager: Displayed com.tencent.mm/.ui.tools.ShareToTimeLineUI: +226ms
2018-11-09 18:14:10.590 767-767/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: LAUNCH OFF
2018-11-09 18:14:10.655 4858-4906/? I/native-tag: GetResults size ret 0
2018-11-09 18:14:10.655 4858-4906/? I/native-tag: GetCodeDetectInfo size ret 1
2018-11-09 18:14:10.660 4858-4906/? I/native-tag: Release id:0
2018-11-09 18:14:10.785 614-614/? D/SurfaceFlinger: duplicate layer name: changing Surface(name=39bbc6d com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI)/@0x8679eb4 - animation-leash to Surface(name=39bbc6d com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI)/@0x8679eb4 - animation-leash#1
2018-11-09 18:14:10.790 614-614/? D/SurfaceFlinger: duplicate layer name: changing Surface(name=Dim Layer for - Task=12848)/@0x1bc7652 - animation-leash to Surface(name=Dim Layer for - Task=12848)/@0x1bc7652 - animation-leash#1
2018-11-09 18:14:10.796 1187-12732/? I/ActivityManager: START u0 {cmp=com.tencent.mm/.plugin.sns.ui.SnsUploadUI (has extras)} from uid 10121
2018-11-09 18:14:10.799 767-767/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: LAUNCH ON
2018-11-09 18:14:10.817 4858-4858/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6673ce2
2018-11-09 18:14:10.897 4858-4858/? D/ViewRootImpl[SnsUploadUI]: changeCanvasOpacity: opaque=true
2018-11-09 18:14:10.971 4858-4858/? I/AssistStructure: Flattened final assist data: 9272 bytes, containing 1 windows, 44 views
2018-11-09 18:14:10.980 1187-1224/? I/ActivityManager: Displayed com.tencent.mm/.plugin.sns.ui.SnsUploadUI: +164ms
2018-11-09 18:14:10.991 767-767/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: LAUNCH OFF
2018-11-09 18:14:11.046 614-635/? W/SurfaceFlinger: Attempting to set client state on removed layer: com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI#0
2018-11-09 18:14:11.046 614-635/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=12848#0
2018-11-09 18:14:11.046 614-635/? W/SurfaceFlinger: Attempting to destroy on removed layer: com.tencent.mm/com.tencent.mm.ui.tools.ShareToTimeLineUI#0
2018-11-09 18:14:11.046 614-635/? W/SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=12848#0

**Comment by QiChaoLau** [comment]
分享并没有报错，停止运行是偶发性的，我怀疑应该是OOM。

**Comment by shichaohui** [comment]
更新了代码，你再试试看还有问题没。
