### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2

### ISSUE THREAD

**Issue by jiaoyongzhi** [shichaohui/WXShareMultiImage#22]
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at android.util.LongArray.checkBounds(LongArray.java:220)
	at android.util.LongArray.get(LongArray.java:169)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:974)
	at com.sch.share.service.WXShareMultiImageService.selectImage(WXShareMultiImageService.kt:162)
	at com.sch.share.service.WXShareMultiImageService.onAccessibilityEvent(WXShareMultiImageService.kt:60)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1538)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1724)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
Back traces ends.

**Comment by jiaoyongzhi** [comment]
VIVO V1901A   系统安卓9

**Comment by shichaohui** [comment]
分享方案已更新，请更新到最新版本。
